<?php

return [
    'roles' => [
        'super-admin' => [
            'name' => 'Super Admin',
            'description' => 'Full system access.',
            'permissions' => ['*'],
        ],
        'admin' => [
            'name' => 'Admin',
            'description' => 'System administrator for users, courses, learning content, enrollments, and reports.',
            'permissions' => [
                'dashboard.view',
                'users.view', 'users.create', 'users.update', 'users.delete', 'users.restore', 'users.export',
                'students.view', 'students.create', 'students.update', 'students.delete', 'students.export',
                'instructors.view', 'instructors.create', 'instructors.update', 'instructors.delete',
                'courses.view', 'courses.create', 'courses.update', 'courses.delete', 'courses.publish', 'courses.archive', 'courses.export',
                'categories.view', 'categories.create', 'categories.update', 'categories.delete',
                'chapters.view', 'chapters.create', 'chapters.update', 'chapters.delete', 'chapters.reorder',
                'contents.view', 'contents.create', 'contents.update', 'contents.delete', 'contents.publish', 'contents.archive', 'contents.reorder',
                'videos.view', 'videos.create', 'videos.update', 'videos.delete',
                'documents.view', 'documents.create', 'documents.update', 'documents.delete', 'documents.download',
                'quizzes.view', 'quizzes.create', 'quizzes.update', 'quizzes.delete', 'quizzes.publish',
                'questions.view', 'questions.create', 'questions.update', 'questions.delete', 'questions.reorder',
                'assignments.view', 'assignments.create', 'assignments.update', 'assignments.delete', 'assignments.grade',
                'enrollments.view', 'enrollments.create', 'enrollments.update', 'enrollments.delete',
                'progress.view', 'progress.view_own', 'progress.export',
                'quiz_results.view', 'quiz_results.view_own', 'quiz_results.export',
                'grades.view', 'grades.view_own', 'grades.update', 'grades.export',
                'certificates.view', 'certificates.create', 'certificates.download', 'certificates.verify',
                'reports.view', 'reports.export',
                'roles.view', 'roles.create', 'roles.update', 'roles.delete',
                'permissions.view', 'permissions.assign',
                'settings.view',
            ],
        ],
        'instructor' => [
            'name' => 'Instructor / Teacher',
            'description' => 'Teaching user with course-content permissions scoped by course ownership or assignment.',
            'permissions' => [
                'dashboard.view',
                'courses.view', 'courses.create', 'courses.update',
                'chapters.view', 'chapters.create', 'chapters.update', 'chapters.delete', 'chapters.reorder',
                'contents.view', 'contents.create', 'contents.update', 'contents.delete', 'contents.reorder',
                'videos.view', 'videos.create', 'videos.update', 'videos.delete',
                'documents.view', 'documents.create', 'documents.update', 'documents.delete', 'documents.download',
                'quizzes.view', 'quizzes.create', 'quizzes.update', 'quizzes.delete',
                'questions.view', 'questions.create', 'questions.update', 'questions.delete', 'questions.reorder',
                'assignments.view', 'assignments.create', 'assignments.update', 'assignments.delete', 'assignments.grade',
                'students.view', 'progress.view', 'progress.view_own',
                'quiz_results.view', 'quiz_results.view_own',
                'grades.view', 'grades.view_own', 'grades.update',
                'reports.view',
            ],
        ],
        'course-manager' => [
            'name' => 'Course Manager',
            'description' => 'Manages course structure, publishing, categories, and course reports.',
            'permissions' => [
                'dashboard.view',
                'courses.view', 'courses.create', 'courses.update', 'courses.delete', 'courses.publish', 'courses.archive', 'courses.export',
                'categories.view', 'categories.create', 'categories.update', 'categories.delete',
                'chapters.view', 'chapters.create', 'chapters.update', 'chapters.delete', 'chapters.reorder',
                'contents.view', 'contents.create', 'contents.update', 'contents.delete', 'contents.publish', 'contents.archive', 'contents.reorder',
                'videos.view', 'videos.create', 'videos.update', 'videos.delete',
                'documents.view', 'documents.create', 'documents.update', 'documents.delete', 'documents.download',
                'quizzes.view', 'quizzes.create', 'quizzes.update', 'quizzes.delete', 'quizzes.publish',
                'questions.view', 'questions.create', 'questions.update', 'questions.delete', 'questions.reorder',
                'reports.view', 'reports.export', 'progress.view', 'progress.view_own',
            ],
        ],
        'student' => [
            'name' => 'Student',
            'description' => 'Learner access to enrolled courses, own progress, quiz results, grades, and certificates.',
            'permissions' => [
                'dashboard.view',
                'courses.view',
                'contents.view',
                'videos.view',
                'documents.view', 'documents.download',
                'quizzes.view',
                'assignments.view', 'assignments.create',
                'enrollments.view', 'enrollments.create',
                'progress.view_own',
                'quiz_results.view_own',
                'grades.view_own',
                'certificates.view', 'certificates.download', 'certificates.verify',
            ],
        ],
        'reviewer' => [
            'name' => 'Reviewer',
            'description' => 'Reviews learning materials and approves or rejects content quality.',
            'permissions' => [
                'dashboard.view',
                'courses.view',
                'chapters.view',
                'contents.view', 'contents.update',
                'videos.view',
                'documents.view',
                'quizzes.view',
                'questions.view',
                'progress.view', 'progress.view_own',
                'reports.view',
            ],
        ],
        'support' => [
            'name' => 'Support',
            'description' => 'Customer and student support with limited student and enrollment visibility.',
            'permissions' => [
                'dashboard.view',
                'users.view',
                'students.view', 'students.update',
                'courses.view',
                'enrollments.view',
                'progress.view', 'progress.view_own',
                'quiz_results.view',
                'grades.view',
            ],
        ],
    ],

    'permissions' => [
        'Dashboard' => ['dashboard.view'],
        'Users' => ['users.view', 'users.create', 'users.update', 'users.delete', 'users.restore', 'users.export'],
        'Students' => ['students.view', 'students.create', 'students.update', 'students.delete', 'students.export'],
        'Instructors' => ['instructors.view', 'instructors.create', 'instructors.update', 'instructors.delete'],
        'Courses' => ['courses.view', 'courses.create', 'courses.update', 'courses.delete', 'courses.publish', 'courses.archive', 'courses.export'],
        'Course Categories' => ['categories.view', 'categories.create', 'categories.update', 'categories.delete'],
        'Chapters' => ['chapters.view', 'chapters.create', 'chapters.update', 'chapters.delete', 'chapters.reorder'],
        'Content' => ['contents.view', 'contents.create', 'contents.update', 'contents.delete', 'contents.publish', 'contents.archive', 'contents.reorder'],
        'Videos' => ['videos.view', 'videos.create', 'videos.update', 'videos.delete'],
        'Documents' => ['documents.view', 'documents.create', 'documents.update', 'documents.delete', 'documents.download'],
        'Quizzes' => ['quizzes.view', 'quizzes.create', 'quizzes.update', 'quizzes.delete', 'quizzes.publish'],
        'Questions' => ['questions.view', 'questions.create', 'questions.update', 'questions.delete', 'questions.reorder'],
        'Assignments' => ['assignments.view', 'assignments.create', 'assignments.update', 'assignments.delete', 'assignments.grade'],
        'Enrollments' => ['enrollments.view', 'enrollments.create', 'enrollments.update', 'enrollments.delete'],
        'Student Progress' => ['progress.view', 'progress.view_own', 'progress.export'],
        'Quiz Results' => ['quiz_results.view', 'quiz_results.view_own', 'quiz_results.export'],
        'Grades' => ['grades.view', 'grades.view_own', 'grades.update', 'grades.export'],
        'Certificates' => ['certificates.view', 'certificates.create', 'certificates.download', 'certificates.verify'],
        'Reports' => ['reports.view', 'reports.export'],
        'Roles' => ['roles.view', 'roles.create', 'roles.update', 'roles.delete'],
        'Permissions' => ['permissions.view', 'permissions.assign'],
        'Settings' => ['settings.view', 'settings.update'],
    ],
];
